services:
  vpn:
    container_name: kame-admin.ryokan.org
    hostname: vpnadminryokan.org
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '1gb'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./kame.ovpn:/etc/openvpn/kame.ovpn:ro
      - ../../home/kame@admin.ryokan.org:/home/kame
    networks:
      - vpnadminryokan.org_network

networks:
  vpnadminryokan.org_network:
    driver: bridge
