services:
  vpn:
    container_name: kamie-admin.kamie.app
    hostname: vpnadminkamie.app
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '1gb'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./kamie.ovpn:/etc/openvpn/kamie.ovpn:ro
      - ../../home/kamie@admin.kamie.app:/home/kamie
    networks:
      - vpnadminkamie.app_network

networks:
  vpnadminkamie.app_network:
    driver: bridge
