from typing import Union
from enum import Enum

class Label(str, Enum):
    LOG_ALREADY_RUNNING = "log.already_running"
    LOG_XHOST_ENABLED = "log.xhost_enabled"
    LOG_XHOST_DISPLAY_ERROR = "log.xhost_display_error"
    LOG_XHOST_ERROR = "log.xhost_error"
    LOG_STRUCTURE_CHECK = "log.structure_check"
    LOG_STRUCTURE_OK = "log.structure_ok"
    LOG_CLOSE_APPLICATION = "log.close_application"
    LOG_JSON_READ_ERROR = "log.json_read_error"
    LOG_CLIENT_NOT_FOUND = "log.client_not_found"
    LOG_CONFIG_MISSING = "log.config_missing"
    LOG_CLIENT_ADDING = "log.client_adding"
    LOG_CONFIG_IGNORED = "log.config_ignored"
    LOG_PROFILE_MISSING = "log.profile_missing"
    LOG_FILE_MUSTEXIST = "log.file_mustexist"
    LOG_FOLDER_MUSTEXIST = "log.folder_mustexist"
    LOG_FILE_CREATED = "log.file_created"
    LOG_FOLDER_CREATED = "log.folder_created"
    LOG_DOCK_FILES_GENERATED = "log.dock_files_generated"
    LOG_DELETE_VPN = "log.delete_vpn"
    LOG_GLOBAL_OPEN_SHELL = "log.global_open_shell"
    LOG_CLIENT_OPEN_SHELL = "log.client_open_shell"
    LOG_GLOBAL_OPEN_SHELL_ERROR = "log.global_open_shell_error"
    LOG_CLIENT_OPEN_SHELL_ERROR = "log.client_open_shell_error"
    LOG_GLOBAL_OPEN_CHROMIUM = "log.global_open_chromium"
    LOG_CLIENT_OPEN_CHROMIUM = "log.client_open_chromium"
    LOG_GLOBAL_OPEN_CHROMIUM_ERROR = "log.global_open_chromium_error"
    LOG_CLIENT_OPEN_CHROMIUM_ERROR = "log.client_open_chromium_error"
    LOG_GLOBAL_START_VPN = "log.global_start_vpn"
    LOG_CLIENT_START_VPN = "log.client_start_vpn"
    LOG_GLOBAL_START_VPN_ERROR = "log.global_start_vpn_error"
    LOG_CLIENT_START_VPN_ERROR = "log.client_start_vpn_error"
    LOG_VPNPANEL_GLOBAL_START_SUCCESS = "log.vpnpanel_global_start_success"
    LOG_VPNPANEL_CLIENT_START_SUCCESS = "log.vpnpanel_client_start_success"
    LOG_GLOBAL_STOP_VPN = "log.global_stop_vpn"
    LOG_CLIENT_STOP_VPN = "log.client_stop_vpn"
    LOG_GLOBAL_STOP_VPN_ERROR = "log.global_stop_vpn_error"
    LOG_CLIENT_STOP_VPN_ERROR = "log.client_stop_vpn_error"
    LOG_VPNPANEL_GLOBAL_STOP_SUCCESS = "log.vpnpanel_global_stop_success"
    LOG_VPNPANEL_CLIENT_STOP_SUCCESS = "log.vpnpanel_client_stop_success"
    LOG_CLIENT_LOG_STDOUT_LABEL = "log.client_log_stdout_label"
    LOG_CLIENT_LOG_APPEND_ERROR = "log.client_log_append_error"
    LOG_CLIENT_LOG_CLEAR_ERROR = "log.client_log_clear_error"
    LOG_CLIENT_ADDED = "log.client_added"
    THEMES_SYSTEM = "themes.system"
    THEMES_LIGHT = "themes.light"
    THEMES_DARK = "themes.dark"

    UI_MAIN_APP_TITLE = "ui_main.app_title"
    UI_MAIN_LABEL_CLIENTS_NAME = "ui_main.label_clients_name"
    UI_MAIN_LABEL_SETTINGS_NAME = "ui_main.label_settings_name"
    UI_MAIN_LABEL_ADD_CLIENT = "ui_main.label_add_client"
    UI_MAIN_LABEL_CONSOLE_LOGS = "ui_main.label_console_logs"
    UI_MAIN_LABEL_MANAGE_PROFILES = "ui_main.label_manage_profiles"
    UI_MAIN_LABEL_QUIT_APP = "ui_main.label_quit_app"
    UI_MAIN_LABEL_THEME_MODE = "ui_main.label_theme_mode"
    UI_MAIN_LABEL_THEME_SELECTOR = "ui_main.label_theme_selector"
    UI_MAIN_LABEL_LANG_SELECTOR = "ui_main.label_lang_selector"
    UI_MAIN_LABEL_TOOLTIP_TOGGLER = "ui_main.label_tooltip_toggler"
    UI_MAIN_LABEL_VIEW_SWITCHER = "ui_main.label_view_switcher"
    UI_MAIN_LABEL_COMPACT_TITLE = "ui_main.label_compact_title"
    UI_MAIN_LABEL_NO_CLIENTS = "ui_main.label_no_clients"

    UI_CLIENT_PANEL_LABEL_CLIENT_NAME = "ui_client_panel.label_client_name"
    UI_CLIENT_PANEL_LABEL_CLIENT_STATUS = "ui_client_panel.label_client_status"
    UI_CLIENT_PANEL_LABEL_PROFILE = "ui_client_panel.label_profile"
    UI_CLIENT_PANEL_LABEL_NO_PROFILE = "ui_client_panel.label_no_profile"
    UI_CLIENT_PANEL_LABEL_CHECKBOX_AUTOSTART = "ui_client_panel.label_checkbox_autostart"
    UI_CLIENT_PANEL_LABEL_CHECKBOX_FAVORITE = "ui_client_panel.label_checkbox_favorite"
    UI_CLIENT_PANEL_LABEL_LAST_ACTION = "ui_client_panel.label_last_action"
    UI_CLIENT_PANEL_LABEL_SHELL = "ui_client_panel.label_shell"
    UI_CLIENT_PANEL_LABEL_CHROMIUM = "ui_client_panel.label_chromium"
    UI_CLIENT_PANEL_LABEL_START_VPN = "ui_client_panel.label_start_vpn"
    UI_CLIENT_PANEL_LABEL_STOP_VPN = "ui_client_panel.label_stop_vpn"
    UI_CLIENT_PANEL_LABEL_REFRESH_VPN = "ui_client_panel.label_refresh_vpn"
    UI_CLIENT_PANEL_LABEL_DELETE_VPN = "ui_client_panel.label_delete_vpn"
    UI_CLIENT_PANEL_LABEL_SHELL_SHORT = "ui_client_panel.label_shell_short"
    UI_CLIENT_PANEL_LABEL_CHROMIUM_SHORT = "ui_client_panel.label_chromium_short"
    UI_CLIENT_PANEL_LABEL_START_VPN_SHORT = "ui_client_panel.label_start_vpn_short"
    UI_CLIENT_PANEL_LABEL_STOP_VPN_SHORT = "ui_client_panel.label_stop_vpn_short"
    UI_CLIENT_PANEL_LABEL_REFRESH_VPN_SHORT = "ui_client_panel.label_refresh_vpn_short"
    UI_CLIENT_PANEL_LABEL_DELETE_VPN_SHORT = "ui_client_panel.label_delete_vpn_short"
    UI_CLIENT_PANEL_LABEL_CHECKING = "ui_client_panel.label_checking"
    UI_CLIENT_PANEL_LABEL_ERROR = "ui_client_panel.label_error"
    UI_CLIENT_PANEL_MSG_TITLE_VPN_REFRESH_WARNING = "ui_client_panel.msg_title_vpn_refresh_warning"
    UI_CLIENT_PANEL_MSG_CONTENT_VPN_REFRESH_WARNING = "ui_client_panel.msg_content_vpn_refresh_warning"
    UI_CLIENT_PANEL_MSG_TITLE_VPN_DELETE_ERROR = "ui_client_panel.msg_title_vpn_delete_error"
    UI_CLIENT_PANEL_MSG_CONTENT_VPN_DELETE_ERROR = "ui_client_panel.msg_content_vpn_delete_error"
    UI_CLIENT_PANEL_MSG_TITLE_VPN_DELETE_CONFIRM = "ui_client_panel.msg_title_vpn_delete_confirm"
    UI_CLIENT_PANEL_MSG_CONTENT_VPN_DELETE_CONFIRM = "ui_client_panel.msg_content_vpn_delete_confirm"
    UI_CLIENT_PANEL_MSG_TITLE_VPN_DELETED = "ui_client_panel.msg_title_vpn_deleted"
    UI_CLIENT_PANEL_MSG_CONTENT_VPN_DELETED = "ui_client_panel.msg_content_vpn_deleted"

    UI_ADD_CLIENT_WINDOW_NAME = "ui_add_client.window_name"
    UI_ADD_CLIENT_BUTTON_SELECT_OVPN = "ui_add_client.button_select_ovpn"
    UI_ADD_CLIENT_LABEL_VPN_USER = "ui_add_client.label_vpn_user"
    UI_ADD_CLIENT_LABEL_VPN_NAME = "ui_add_client.label_vpn_name"
    UI_ADD_CLIENT_LABEL_DOMAIN_NAME = "ui_add_client.label_domain_name"
    UI_ADD_CLIENT_LABEL_PROFILE_LIST = "ui_add_client.label_profile_list"
    UI_ADD_CLIENT_LABEL_PROFILE_SELECT = "ui_add_client.label_profile_select"
    UI_ADD_CLIENT_BUTTON_SUBMIT = "ui_add_client.button_submit"
    UI_ADD_CLIENT_MSG_TITLE_ERROR = "ui_add_client.msg_title_error"
    UI_ADD_CLIENT_MSG_CONTENT_MISSING_FIELDS_ERROR = "ui_add_client.msg_content_missing_fields_error"
    UI_ADD_CLIENT_MSG_TITLE_SELECT_OVPN = "ui_add_client.msg_title_select_ovpn"
    UI_ADD_CLIENT_MSG_TYPE_SELECT_OVPN = "ui_add_client.msg_type_select_ovpn"
    UI_ADD_CLIENT_MSG_TITLE__VPN_ALREADY_EXISTS = "ui_add_client.msg_title__vpn_already_exists"
    UI_ADD_CLIENT_MSG__CONTENT_VPN_ALREADY_EXISTS = "ui_add_client.msg__content_vpn_already_exists"

    UI_MANAGE_PROFILES_WINDOW_NAME = "ui_manage_profiles.window_name"
    UI_MANAGE_PROFILES_BUTTON_ADD_PROFILE = "ui_manage_profiles.button_add_profile"
    UI_MANAGE_PROFILES_BUTTON_RENAME_PROFILE = "ui_manage_profiles.button_rename_profile"
    UI_MANAGE_PROFILES_BUTTON_DELETE_PROFILE = "ui_manage_profiles.button_delete_profile"
    UI_MANAGE_PROFILES_BUTTON_REFRESH_PROFILE_LIST = "ui_manage_profiles.button_refresh_profile_list"
    UI_MANAGE_PROFILES_MSG_ADD_PROFILE_SELECT = "ui_manage_profiles.msg_add_profile_select"
    UI_MANAGE_PROFILES_MSG_TITLE_ADD_PROFILE_ALREADY_EXIST = "ui_manage_profiles.msg_title_add_profile_already_exist"
    UI_MANAGE_PROFILES_MSG_CONTENT_ADD_PROFILE_ALREADY_EXIST = "ui_manage_profiles.msg_content_add_profile_already_exist"
    UI_MANAGE_PROFILES_MSG_TITLE_PROFILE_CREATED = "ui_manage_profiles.msg_title_profile_created"
    UI_MANAGE_PROFILES_MSG_CONTENT_PROFILE_CREATED = "ui_manage_profiles.msg_content_profile_created"
    UI_MANAGE_PROFILES_MSG_TITLE_CANNOT_DELETE_PROFILE = "ui_manage_profiles.msg_title_cannot_delete_profile"
    UI_MANAGE_PROFILES_MSG_CONTENT_CANNOT_DELETE_PROFILE = "ui_manage_profiles.msg_content_cannot_delete_profile"
    UI_MANAGE_PROFILES_MSG_TITLE_WARNING_DELETE_PROFILE = "ui_manage_profiles.msg_title_warning_delete_profile"
    UI_MANAGE_PROFILES_MSG_CONTENT_WARNING_DELETE_PROFILE = "ui_manage_profiles.msg_content_warning_delete_profile"
    UI_MANAGE_PROFILES_MSG_TITLE_PROFILE_DELETED = "ui_manage_profiles.msg_title_profile_deleted"
    UI_MANAGE_PROFILES_MSG_CONTENT_PROFILE_DELETED = "ui_manage_profiles.msg_content_profile_deleted"
    UI_MANAGE_PROFILES_MSG_TITLE_PROFILE_RENAME = "ui_manage_profiles.msg_title_profile_rename"
    UI_MANAGE_PROFILES_MSG_CONTENT_PROFILE_RENAME = "ui_manage_profiles.msg_content_profile_rename"
    UI_MANAGE_PROFILES_MSG_TITLE_PROFILE_RENAME_ERROR = "ui_manage_profiles.msg_title_profile_rename_error"
    UI_MANAGE_PROFILES_MSG_CONTENT_PROFILE_RENAME_ERROR = "ui_manage_profiles.msg_content_profile_rename_error"
    UI_MANAGE_PROFILES_MSG_TITLE_PROFILE_RENAME_WARNING = "ui_manage_profiles.msg_title_profile_rename_warning"
    UI_MANAGE_PROFILES_MSG_CONTENT_PROFILE_RENAME_WARNING = "ui_manage_profiles.msg_content_profile_rename_warning"
    UI_MANAGE_PROFILES_MSG_TITLE_PROFILE_RENAME_SUCCESS = "ui_manage_profiles.msg_title_profile_rename_success"
    UI_MANAGE_PROFILES_MSG_CONTENT_PROFILE_RENAME_SUCCESS = "ui_manage_profiles.msg_content_profile_rename_success"

    UI_CONSOLE_LOGS_WINDOW_NAME = "ui_console_logs.window_name"
    UI_CONSOLE_LOGS_BUTTON_PURGE_GLOBAL_LOGS = "ui_console_logs.button_purge_global_logs"
    UI_CONSOLE_LOGS_BUTTON_PURGE_CLIENT_LOGS = "ui_console_logs.button_purge_client_logs"
    UI_CONSOLE_LOGS_LABEL_GLOBAL_LOG = "ui_console_logs.label_global_log"
    UI_CONSOLE_LOGS_LABEL_CLIENT_LOG = "ui_console_logs.label_client_log"

    UI_SYSTRAY_BUTTON_SYSTRAY_QUIT = "ui_systray.button_systray_quit"

    LOG_ACTIONS_ADD_CLIENT = "log_actions.add_client"
    LOG_ACTIONS_DELETE_CLIENT = "log_actions.delete_client"
    LOG_ACTIONS_ADD_PROFILE = "log_actions.add_profile"
    LOG_ACTIONS_RENAME_PROFILE = "log_actions.rename_profile"
    LOG_ACTIONS_DELETE_PROFILE = "log_actions.delete_profile"
    LOG_ACTIONS_PURGE_LOGS = "log_actions.purge_logs"
    LOG_ACTIONS_START_VPN = "log_actions.start_vpn"
    LOG_ACTIONS_STOP_VPN = "log_actions.stop_vpn"
    LOG_ACTIONS_REFRESH_VPN = "log_actions.refresh_vpn"
    LOG_ACTIONS_ADD_SUCCESS = "log_actions.add_success"
    LOG_ACTIONS_DELETE_SUCCESS = "log_actions.delete_success"
    LOG_ACTIONS_RENAME_SUCCESS = "log_actions.rename_success"
    LOG_ACTIONS_PURGE_SUCCESS = "log_actions.purge_success"
    LOG_ACTIONS_START_SUCCESS = "log_actions.start_success"
    LOG_ACTIONS_STOP_SUCCESS = "log_actions.stop_success"
    LOG_ACTIONS_REFRESH_SUCCESS = "log_actions.refresh_success"

    STATUS_MANAGER_READY = "status_manager.ready"
    STATUS_OVPN_NOFILE = "status_ovpn.nofile"
    STATUS_OVPN_SELECTED = "status_ovpn.selected"
    STATUS_PROFILE_MISSING = "status_profile.missing"
    STATUS_PROFILE_OK = "status_profile.ok"
    
    STATUS_VPN_CONNECTED = "status_vpn.connected"
    STATUS_VPN_DISCONNECTED = "status_vpn.disconnected"
    STATUS_VPN_ERROR = "status_vpn.error"
    STATUS_VPN_CHECKING = "status_vpn.checking"
    STATUS_VPN_DELETED = "status_vpn.deleted"

    ACTIONS_NO_RECENT_ACTION = "actions.no_recent_action"
    ACTIONS_START_VPN = "actions.start_vpn"
    ACTIONS_STOP_VPN = "actions.stop_vpn"
    ACTIONS_REFRESH_VPN = "actions.refresh_vpn"
    ACTIONS_OPEN_TERMINAL = "actions.open_terminal"
    ACTIONS_OPEN_BROWSER = "actions.open_browser"
    ACTIONS_ADD_CLIENT = "actions.add_client"
    ACTIONS_DELETE_CLIENT = "actions.delete_client"
    ACTIONS_ADD_PROFILE = "actions.add_profile"
    ACTIONS_RENAME_PROFILE = "actions.rename_profile"
    ACTIONS_DELETE_PROFILE = "actions.delete_profile"

    COMPACTCARD_AUTOSTARTING = "compactcard.autostarting"
    COMPACTCARD_NOTAUTOSTARTING = "compactcard.notautostarting"

    FULLCARD_AUTOSTARTING = "fullcard.autostarting"
    FULLCARD_NOTAUTOSTARTING = "fullcard.notautostarting"

    BUTTONS_OK = "buttons.ok"
    BUTTONS_CANCEL = "buttons.cancel"
    BUTTONS_YES = "buttons.yes"
    BUTTONS_NO = "buttons.no"
    BUTTONS_RETRY = "buttons.retry"
    BUTTONS_ABORT = "buttons.abort"
    BUTTONS_IGNORE = "buttons.ignore"


    def __call__(self, **kwargs) -> Union[dict, "Label"]:
        if not kwargs:
            return self
        return {"key": self, **kwargs}